'use strict';
(()=>{
const el=id=>document.getElementById(id);
let ready=false,recorder=null,stream=null,timer=null,busy=false,canceled=false,installPrompt=null;
const message=(text,error=false)=>{el('ai-status').textContent=text;el('ai-status').classList.toggle('error',error)};
function buttons(){el('ai-record').disabled=busy||!ready||!el('consent').checked;el('consent').disabled=busy||!!recorder;el('mic').disabled=busy||!!recorder||!(window.SpeechRecognition||window.webkitSpeechRecognition)}
function release(){if(stream)stream.getTracks().forEach(track=>track.stop());stream=null;clearTimeout(timer);recorder=null;buttons()}
async function jsonRequest(url,options){const response=await fetch(url,{...options,signal:AbortSignal.timeout(90000)});const data=await response.json();if(!response.ok)throw Error(data.error||'Não foi possível analisar a conversa.');return data}
async function analyze(blob){busy=true;buttons();message('Enviando áudio para análise…');try{const job=await jsonRequest('/api/conversation',{method:'POST',headers:{'Content-Type':blob.type||'audio/webm'},body:blob});let result;for(let i=0;i<100;i++){await new Promise(resolve=>setTimeout(resolve,3000));result=await jsonRequest('/api/conversation/'+encodeURIComponent(job.id));if(result.status==='completed')break;if(result.status==='error')throw Error(result.error);message('A IA está separando as vozes…')}if(result.status!=='completed')throw Error('A análise ainda não terminou. Tente uma gravação mais curta.');el('turns').replaceChildren();for(const utterance of result.utterances||[]){const card=document.createElement('article');card.className='card';const name=document.createElement('strong');name.style.color='#7dd3fc';name.textContent='Pessoa '+(utterance.speaker??'?');const text=document.createElement('p');text.textContent=utterance.text;const button=document.createElement('button');button.className='text-button';button.textContent='Traduzir esta fala →';button.onclick=()=>{el('captured').value=utterance.text;el('captured').dispatchEvent(new Event('input'));el('translate').click();el('captured').scrollIntoView({behavior:'smooth',block:'center'})};card.append(name,text,button);el('turns').append(card)}message(result.utterances?.length?'Conversa pronta. Toque em uma fala para traduzi-la.':'Nenhuma fala detectada. Grave novamente com menos ruído.')}catch(error){message(error.message||'Falha na análise. Tente novamente.',true)}finally{busy=false;buttons()}}
el('consent').onchange=buttons;
el('ai-record').onclick=async()=>{if(recorder){el('ai-record').disabled=true;recorder.stop();return}if(el('mic').getAttribute('aria-pressed')==='true'){message('Pare o microfone do tradutor antes de gravar a conversa.',true);return}busy=true;buttons();message('Aguardando acesso ao microfone…');try{if(!window.isSecureContext)throw Error('A gravação exige HTTPS ou localhost.');if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('Este navegador não permite gravar áudio.');stream=await navigator.mediaDevices.getUserMedia({audio:true});const type=['audio/webm;codecs=opus','audio/mp4','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(stream,type?{mimeType:type}:undefined);const chunks=[];canceled=false;recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};recorder.onstop=()=>{const mime=recorder.mimeType;const blob=new Blob(chunks,{type:mime});release();el('ai-record').textContent='Gravar conversa';if(!canceled&&blob.size)analyze(blob);else message('Gravação cancelada. Nenhum áudio foi enviado.')};recorder.onerror=()=>{canceled=true;message('Falha no microfone. Grave novamente.',true);if(recorder?.state==='recording')recorder.stop();else release()};recorder.start();busy=false;buttons();el('ai-record').textContent='Parar e analisar';message('Gravando conversa… Limite de 60 segundos.');timer=setTimeout(()=>{if(recorder?.state==='recording')recorder.stop()},60000)}catch(error){busy=false;release();message(error.name==='NotAllowedError'?'Permita o microfone nas configurações do navegador.':error.message,true)}};
el('erase-ai').onclick=()=>{el('turns').replaceChildren();message('Resultado removido deste aparelho. O áudio enviado segue a política de retenção da AssemblyAI.')};
fetch('/api/status').then(response=>response.json()).then(data=>{ready=data.ai;message(ready?'IA disponível. Autorize o envio e grave a conversa.':'IA aguardando configuração no servidor. O tradutor por texto e voz continua disponível.');buttons()}).catch(()=>message('Abra o app pelo servidor Sintra para usar a IA.',true));
if('serviceWorker' in navigator&&window.isSecureContext)navigator.serviceWorker.register('./sw.js').catch(()=>{el('install-help').textContent='Não foi possível preparar a instalação. Recarregue usando HTTPS.'});
window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;el('install').hidden=false});
el('install').onclick=async()=>{if(!installPrompt)return;await installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;el('install').hidden=true};
window.addEventListener('appinstalled',()=>{el('install').hidden=true;el('install-help').textContent='Sintra instalado na sua tela inicial.'});
window.addEventListener('pagehide',()=>{canceled=true;if(recorder?.state==='recording')recorder.stop();if(stream)stream.getTracks().forEach(track=>track.stop())});
})();
